// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(APIContext))]
    [Migration("20260405055711_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlunoTurma", b =>
                {
                    b.Property<int>("AlunosId")
                        .HasColumnType("integer")
                        .HasColumnName("alunos_id");

                    b.Property<int>("TurmasId")
                        .HasColumnType("integer")
                        .HasColumnName("turmas_id");

                    b.HasKey("AlunosId", "TurmasId")
                        .HasName("pk_aluno_turma");

                    b.HasIndex("TurmasId")
                        .HasDatabaseName("ix_aluno_turma_turmas_id");

                    b.ToTable("aluno_turma", (string)null);
                });

            modelBuilder.Entity("CriterioTurma", b =>
                {
                    b.Property<int>("CriteriosId")
                        .HasColumnType("integer")
                        .HasColumnName("criterios_id");

                    b.Property<int>("TurmasId")
                        .HasColumnType("integer")
                        .HasColumnName("turmas_id");

                    b.HasKey("CriteriosId", "TurmasId")
                        .HasName("pk_criterio_turma");

                    b.HasIndex("TurmasId")
                        .HasDatabaseName("ix_criterio_turma_turmas_id");

                    b.ToTable("criterio_turma", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_alunos");

                    b.ToTable("alunos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AlunoGrupo", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("aluno_id");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer")
                        .HasColumnName("grupo_id");

                    b.Property<int>("TurmaId")
                        .HasColumnType("integer")
                        .HasColumnName("turma_id");

                    b.HasKey("AlunoId", "GrupoId")
                        .HasName("pk_aluno_grupo");

                    b.ToTable("aluno_grupo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Criterio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_criterios");

                    b.ToTable("criterios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Nível de Participação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Pontualidade na Entrega de Tarefas"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Capacidade de Trabalhar em Equipe"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Controle Emocional"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Disposição para Compartilhar Tarefas"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Respeito às Individualidades"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Responsabilidade"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Criatividade"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Conhecimento Teórico"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("TurmaId")
                        .HasColumnType("integer")
                        .HasColumnName("turma_id");

                    b.HasKey("Id")
                        .HasName("pk_grupos");

                    b.HasIndex("TurmaId")
                        .HasDatabaseName("ix_grupos_turma_id");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.NotaFinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliadorId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliador_id");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_envio");

                    b.Property<string>("DeviceHash")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("character(65)")
                        .HasColumnName("device_hash")
                        .IsFixedLength();

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer")
                        .HasColumnName("grupo_id");

                    b.Property<int>("SessaoId")
                        .HasColumnType("integer")
                        .HasColumnName("sessao_id");

                    b.HasKey("Id")
                        .HasName("pk_notas_finais");

                    b.HasIndex("AvaliadorId")
                        .HasDatabaseName("ix_notas_finais_avaliador_id");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_notas_finais_grupo_id");

                    b.HasIndex("SessaoId")
                        .HasDatabaseName("ix_notas_finais_sessao_id");

                    b.HasIndex("SessaoId", "AvaliadorId")
                        .IsUnique()
                        .HasDatabaseName("ix_notas_finais_sessao_id_avaliador_id");

                    b.HasIndex("SessaoId", "DeviceHash")
                        .IsUnique()
                        .HasDatabaseName("ix_notas_finais_sessao_id_device_hash");

                    b.ToTable("notas_finais", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.NotaParcial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliadoId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliado_id");

                    b.Property<int>("CriterioId")
                        .HasColumnType("integer")
                        .HasColumnName("criterio_id");

                    b.Property<decimal>("Nota")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("nota");

                    b.Property<int>("NotaFinalId")
                        .HasColumnType("integer")
                        .HasColumnName("nota_final_id");

                    b.HasKey("Id")
                        .HasName("pk_notas_parciais");

                    b.HasIndex("AvaliadoId")
                        .HasDatabaseName("ix_notas_parciais_avaliado_id");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("AvaliadoId"), new[] { "Nota", "CriterioId" });

                    b.HasIndex("CriterioId")
                        .HasDatabaseName("ix_notas_parciais_criterio_id");

                    b.HasIndex("AvaliadoId", "CriterioId")
                        .HasDatabaseName("ix_notas_parciais_avaliado_id_criterio_id");

                    b.HasIndex("NotaFinalId", "AvaliadoId", "CriterioId")
                        .IsUnique()
                        .HasDatabaseName("ix_notas_parciais_nota_final_id_avaliado_id_criterio_id");

                    b.ToTable("notas_parciais", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<string>("TokenPublico")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("token_publico");

                    b.Property<int>("TurmaId")
                        .HasColumnType("integer")
                        .HasColumnName("turma_id");

                    b.HasKey("Id")
                        .HasName("pk_sessoes");

                    b.HasIndex("TurmaId")
                        .HasDatabaseName("ix_sessoes_turma_id");

                    b.ToTable("sessoes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cod");

                    b.Property<decimal>("NotaMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("nota_max");

                    b.HasKey("Id")
                        .HasName("pk_turmas");

                    b.ToTable("turmas", (string)null);
                });

            modelBuilder.Entity("AlunoTurma", b =>
                {
                    b.HasOne("Domain.Entities.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aluno_turma_alunos_alunos_id");

                    b.HasOne("Domain.Entities.Turma", null)
                        .WithMany()
                        .HasForeignKey("TurmasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aluno_turma_turmas_turmas_id");
                });

            modelBuilder.Entity("CriterioTurma", b =>
                {
                    b.HasOne("Domain.Entities.Criterio", null)
                        .WithMany()
                        .HasForeignKey("CriteriosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_criterio_turma_criterios_criterios_id");

                    b.HasOne("Domain.Entities.Turma", null)
                        .WithMany()
                        .HasForeignKey("TurmasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_criterio_turma_turmas_turmas_id");
                });

            modelBuilder.Entity("Domain.Entities.Grupo", b =>
                {
                    b.HasOne("Domain.Entities.Turma", "Turma")
                        .WithMany("Grupos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grupos_turmas_turma_id");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Domain.Entities.NotaFinal", b =>
                {
                    b.HasOne("Domain.Entities.Aluno", "Avaliador")
                        .WithMany()
                        .HasForeignKey("AvaliadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notas_finais_alunos_avaliador_id");

                    b.HasOne("Domain.Entities.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notas_finais_grupos_grupo_id");

                    b.HasOne("Domain.Entities.Sessao", "Sessao")
                        .WithMany("Notasfinais")
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notas_finais_sessoes_sessao_id");

                    b.Navigation("Avaliador");

                    b.Navigation("Grupo");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("Domain.Entities.NotaParcial", b =>
                {
                    b.HasOne("Domain.Entities.Aluno", "Avaliado")
                        .WithMany()
                        .HasForeignKey("AvaliadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notas_parciais_alunos_avaliado_id");

                    b.HasOne("Domain.Entities.Criterio", "Criterio")
                        .WithMany()
                        .HasForeignKey("CriterioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notas_parciais_criterios_criterio_id");

                    b.HasOne("Domain.Entities.NotaFinal", "NotaFinal")
                        .WithMany("NotasParcial")
                        .HasForeignKey("NotaFinalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notas_parciais_notas_finais_nota_final_id");

                    b.Navigation("Avaliado");

                    b.Navigation("Criterio");

                    b.Navigation("NotaFinal");
                });

            modelBuilder.Entity("Domain.Entities.Sessao", b =>
                {
                    b.HasOne("Domain.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessoes_turmas_turma_id");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Domain.Entities.NotaFinal", b =>
                {
                    b.Navigation("NotasParcial");
                });

            modelBuilder.Entity("Domain.Entities.Sessao", b =>
                {
                    b.Navigation("Notasfinais");
                });

            modelBuilder.Entity("Domain.Entities.Turma", b =>
                {
                    b.Navigation("Grupos");
                });
#pragma warning restore 612, 618
        }
    }
}
