// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(APIContext))]
    [Migration("20260616042544_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlunoTurma", b =>
                {
                    b.Property<int>("AlunosId")
                        .HasColumnType("integer")
                        .HasColumnName("alunos_id");

                    b.Property<int>("TurmasId")
                        .HasColumnType("integer")
                        .HasColumnName("turmas_id");

                    b.HasKey("AlunosId", "TurmasId")
                        .HasName("pk_aluno_turma");

                    b.HasIndex("TurmasId")
                        .HasDatabaseName("ix_aluno_turma_turmas_id");

                    b.ToTable("aluno_turma", (string)null);
                });

            modelBuilder.Entity("CriterioTurma", b =>
                {
                    b.Property<int>("CriteriosId")
                        .HasColumnType("integer")
                        .HasColumnName("criterios_id");

                    b.Property<int>("TurmasId")
                        .HasColumnType("integer")
                        .HasColumnName("turmas_id");

                    b.HasKey("CriteriosId", "TurmasId")
                        .HasName("pk_criterio_turma");

                    b.HasIndex("TurmasId")
                        .HasDatabaseName("ix_criterio_turma_turmas_id");

                    b.ToTable("criterio_turma", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_alunos");

                    b.ToTable("alunos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AlunoGrupo", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("aluno_id");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer")
                        .HasColumnName("grupo_id");

                    b.Property<int>("TurmaId")
                        .HasColumnType("integer")
                        .HasColumnName("turma_id");

                    b.HasKey("AlunoId", "GrupoId")
                        .HasName("pk_aluno_grupo");

                    b.ToTable("aluno_grupo", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Criterio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_criterios");

                    b.ToTable("criterios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Nível de Participação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Pontualidade na Entrega de Tarefas"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Capacidade de Trabalhar em Equipe"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Controle Emocional"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Disposição para Compartilhar Tarefas"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Respeito às Individualidades"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Responsabilidade"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Criatividade"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Conhecimento Teórico"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("TurmaId")
                        .HasColumnType("integer")
                        .HasColumnName("turma_id");

                    b.HasKey("Id")
                        .HasName("pk_grupos");

                    b.HasIndex("TurmaId")
                        .HasDatabaseName("ix_grupos_turma_id");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.NotaFinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliadorId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliador_id");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_envio");

                    b.Property<string>("DeviceHash")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("device_hash");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer")
                        .HasColumnName("grupo_id");

                    b.Property<int>("SessaoId")
                        .HasColumnType("integer")
                        .HasColumnName("sessao_id");

                    b.HasKey("Id")
                        .HasName("pk_notas_finais");

                    b.HasIndex("AvaliadorId")
                        .HasDatabaseName("ix_notas_finais_avaliador_id");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_notas_finais_grupo_id");

                    b.HasIndex("SessaoId")
                        .HasDatabaseName("ix_notas_finais_sessao_id");

                    b.HasIndex("SessaoId", "AvaliadorId")
                        .IsUnique()
                        .HasDatabaseName("ix_notas_finais_sessao_id_avaliador_id");

                    b.HasIndex("SessaoId", "DeviceHash")
                        .IsUnique()
                        .HasDatabaseName("ix_notas_finais_sessao_id_device_hash");

                    b.ToTable("notas_finais", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.NotaParcial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliadoId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliado_id");

                    b.Property<int>("CriterioId")
                        .HasColumnType("integer")
                        .HasColumnName("criterio_id");

                    b.Property<decimal>("Nota")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("nota");

                    b.Property<int>("NotaFinalId")
                        .HasColumnType("integer")
                        .HasColumnName("nota_final_id");

                    b.HasKey("Id")
                        .HasName("pk_notas_parciais");

                    b.HasIndex("AvaliadoId")
                        .HasDatabaseName("ix_notas_parciais_avaliado_id");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("AvaliadoId"), new[] { "Nota", "CriterioId" });

                    b.HasIndex("CriterioId")
                        .HasDatabaseName("ix_notas_parciais_criterio_id");

                    b.HasIndex("AvaliadoId", "CriterioId")
                        .HasDatabaseName("ix_notas_parciais_avaliado_id_criterio_id");

                    b.HasIndex("NotaFinalId", "AvaliadoId", "CriterioId")
                        .IsUnique()
                        .HasDatabaseName("ix_notas_parciais_nota_final_id_avaliado_id_criterio_id");

                    b.ToTable("notas_parciais", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_professores");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_professores_user_name");

                    b.ToTable("professores", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer")
                        .HasColumnName("professor_id");

                    b.Property<bool>("Revogado")
                        .HasColumnType("boolean")
                        .HasColumnName("revogado");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ProfessorId")
                        .HasDatabaseName("ix_refresh_tokens_professor_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ResultadoAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer")
                        .HasColumnName("aluno_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("ResultadoGrupoId")
                        .HasColumnType("integer")
                        .HasColumnName("resultado_grupo_id");

                    b.Property<int>("ResultadoSessaoId")
                        .HasColumnType("integer")
                        .HasColumnName("resultado_sessao_id");

                    b.HasKey("Id")
                        .HasName("pk_alunos_resultados");

                    b.HasIndex("ResultadoGrupoId")
                        .HasDatabaseName("ix_alunos_resultados_resultado_grupo_id");

                    b.HasIndex("ResultadoSessaoId")
                        .HasDatabaseName("ix_alunos_resultados_resultado_sessao_id");

                    b.ToTable("alunos_resultados", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ResultadoCriterio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CriterioId")
                        .HasColumnType("integer")
                        .HasColumnName("criterio_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("ResultadoSessaoId")
                        .HasColumnType("integer")
                        .HasColumnName("resultado_sessao_id");

                    b.HasKey("Id")
                        .HasName("pk_criterios_resultados");

                    b.HasIndex("ResultadoSessaoId")
                        .HasDatabaseName("ix_criterios_resultados_resultado_sessao_id");

                    b.ToTable("criterios_resultados", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ResultadoGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("ResultadoSessaoId")
                        .HasColumnType("integer")
                        .HasColumnName("resultado_sessao_id");

                    b.HasKey("Id")
                        .HasName("pk_grupos_resultados");

                    b.HasIndex("ResultadoSessaoId")
                        .HasDatabaseName("ix_grupos_resultados_resultado_sessao_id");

                    b.ToTable("grupos_resultados", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ResultadoNotaFinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvaliadorNome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avaliador_nome");

                    b.Property<int>("AvaliadorResId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliador_res_id");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_envio");

                    b.Property<string>("GrupoNome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupo_nome");

                    b.Property<int>("GrupoResId")
                        .HasColumnType("integer")
                        .HasColumnName("grupo_res_id");

                    b.Property<int>("NotaFinalId")
                        .HasColumnType("integer")
                        .HasColumnName("nota_final_id");

                    b.Property<int>("ResultadoSessaoId")
                        .HasColumnType("integer")
                        .HasColumnName("resultado_sessao_id");

                    b.HasKey("Id")
                        .HasName("pk_nota_finais_resultados");

                    b.HasIndex("ResultadoSessaoId")
                        .HasDatabaseName("ix_nota_finais_resultados_resultado_sessao_id");

                    b.HasIndex("ResultadoSessaoId", "AvaliadorResId")
                        .IsUnique()
                        .HasDatabaseName("ix_nota_finais_resultados_resultado_sessao_id_avaliador_res_id");

                    b.ToTable("nota_finais_resultados", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ResultadoNotaParcial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliadoResId")
                        .HasColumnType("integer")
                        .HasColumnName("avaliado_res_id");

                    b.Property<string>("AvaliadoResNome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avaliado_res_nome");

                    b.Property<int>("CriterioResId")
                        .HasColumnType("integer")
                        .HasColumnName("criterio_res_id");

                    b.Property<string>("CriterioResNome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("criterio_res_nome");

                    b.Property<decimal>("Nota")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("nota");

                    b.Property<int>("NotaParcialId")
                        .HasColumnType("integer")
                        .HasColumnName("nota_parcial_id");

                    b.Property<int>("ResultadoNotaFinalId")
                        .HasColumnType("integer")
                        .HasColumnName("resultado_nota_final_id");

                    b.HasKey("Id")
                        .HasName("pk_notas_parciais_resultados");

                    b.HasIndex("AvaliadoResId")
                        .HasDatabaseName("ix_notas_parciais_resultados_avaliado_res_id");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("AvaliadoResId"), new[] { "Nota", "CriterioResId" });

                    b.HasIndex("CriterioResId")
                        .HasDatabaseName("ix_notas_parciais_resultados_criterio_res_id");

                    b.HasIndex("AvaliadoResId", "CriterioResId")
                        .HasDatabaseName("ix_notas_parciais_resultados_avaliado_res_id_criterio_res_id");

                    b.HasIndex("ResultadoNotaFinalId", "AvaliadoResId", "CriterioResId")
                        .IsUnique()
                        .HasDatabaseName("ix_notas_parciais_resultados_resultado_nota_final_id_avaliado_");

                    b.ToTable("notas_parciais_resultados", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ResultadoSessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<decimal>("NotaMaxima")
                        .HasColumnType("numeric")
                        .HasColumnName("nota_maxima");

                    b.Property<int>("SessaoId")
                        .HasColumnType("integer")
                        .HasColumnName("sessao_id");

                    b.Property<string>("TurmaCod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("turma_cod");

                    b.Property<int>("TurmaId")
                        .HasColumnType("integer")
                        .HasColumnName("turma_id");

                    b.HasKey("Id")
                        .HasName("pk_sessoes_resultados");

                    b.HasIndex("SessaoId")
                        .HasDatabaseName("ix_sessoes_resultados_sessao_id");

                    b.ToTable("sessoes_resultados", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<string>("TokenPublico")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("token_publico");

                    b.Property<int>("TurmaId")
                        .HasColumnType("integer")
                        .HasColumnName("turma_id");

                    b.HasKey("Id")
                        .HasName("pk_sessoes");

                    b.HasIndex("TurmaId")
                        .HasDatabaseName("ix_sessoes_turma_id");

                    b.ToTable("sessoes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cod");

                    b.Property<decimal>("NotaMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("nota_max");

                    b.HasKey("Id")
                        .HasName("pk_turmas");

                    b.ToTable("turmas", (string)null);
                });

            modelBuilder.Entity("AlunoTurma", b =>
                {
                    b.HasOne("Domain.Entities.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aluno_turma_alunos_alunos_id");

                    b.HasOne("Domain.Entities.Turma", null)
                        .WithMany()
                        .HasForeignKey("TurmasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aluno_turma_turmas_turmas_id");
                });

            modelBuilder.Entity("CriterioTurma", b =>
                {
                    b.HasOne("Domain.Entities.Criterio", null)
                        .WithMany()
                        .HasForeignKey("CriteriosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_criterio_turma_criterios_criterios_id");

                    b.HasOne("Domain.Entities.Turma", null)
                        .WithMany()
                        .HasForeignKey("TurmasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_criterio_turma_turmas_turmas_id");
                });

            modelBuilder.Entity("Domain.Entities.Grupo", b =>
                {
                    b.HasOne("Domain.Entities.Turma", "Turma")
                        .WithMany("Grupos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grupos_turmas_turma_id");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Domain.Entities.NotaFinal", b =>
                {
                    b.HasOne("Domain.Entities.Aluno", "Avaliador")
                        .WithMany()
                        .HasForeignKey("AvaliadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notas_finais_alunos_avaliador_id");

                    b.HasOne("Domain.Entities.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notas_finais_grupos_grupo_id");

                    b.HasOne("Domain.Entities.Sessao", "Sessao")
                        .WithMany("Notasfinais")
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notas_finais_sessoes_sessao_id");

                    b.Navigation("Avaliador");

                    b.Navigation("Grupo");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("Domain.Entities.NotaParcial", b =>
                {
                    b.HasOne("Domain.Entities.Aluno", "Avaliado")
                        .WithMany()
                        .HasForeignKey("AvaliadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notas_parciais_alunos_avaliado_id");

                    b.HasOne("Domain.Entities.Criterio", "Criterio")
                        .WithMany()
                        .HasForeignKey("CriterioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notas_parciais_criterios_criterio_id");

                    b.HasOne("Domain.Entities.NotaFinal", "NotaFinal")
                        .WithMany("NotasParcial")
                        .HasForeignKey("NotaFinalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notas_parciais_notas_finais_nota_final_id");

                    b.Navigation("Avaliado");

                    b.Navigation("Criterio");

                    b.Navigation("NotaFinal");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.Professor", "Professor")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_professores_professor_id");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Domain.Entities.ResultadoAluno", b =>
                {
                    b.HasOne("Domain.Entities.ResultadoGrupo", "ResultadoGrupo")
                        .WithMany("Alunos")
                        .HasForeignKey("ResultadoGrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alunos_resultados_grupos_resultados_resultado_grupo_id");

                    b.HasOne("Domain.Entities.ResultadoSessao", "ResultadoSessao")
                        .WithMany("Alunos")
                        .HasForeignKey("ResultadoSessaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alunos_resultados_sessoes_resultados_resultado_sessao_id");

                    b.Navigation("ResultadoGrupo");

                    b.Navigation("ResultadoSessao");
                });

            modelBuilder.Entity("Domain.Entities.ResultadoCriterio", b =>
                {
                    b.HasOne("Domain.Entities.ResultadoSessao", "ResultadoSessao")
                        .WithMany("Criterios")
                        .HasForeignKey("ResultadoSessaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_criterios_resultados_sessoes_resultados_resultado_sessao_id");

                    b.Navigation("ResultadoSessao");
                });

            modelBuilder.Entity("Domain.Entities.ResultadoGrupo", b =>
                {
                    b.HasOne("Domain.Entities.ResultadoSessao", "ResultadoSessao")
                        .WithMany("Grupos")
                        .HasForeignKey("ResultadoSessaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grupos_resultados_sessoes_resultados_resultado_sessao_id");

                    b.Navigation("ResultadoSessao");
                });

            modelBuilder.Entity("Domain.Entities.ResultadoNotaFinal", b =>
                {
                    b.HasOne("Domain.Entities.ResultadoSessao", "ResultadoSessao")
                        .WithMany("NotasFinais")
                        .HasForeignKey("ResultadoSessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nota_finais_resultados_sessoes_resultados_resultado_sessao_");

                    b.Navigation("ResultadoSessao");
                });

            modelBuilder.Entity("Domain.Entities.ResultadoNotaParcial", b =>
                {
                    b.HasOne("Domain.Entities.ResultadoNotaFinal", "ResultadoNotaFinal")
                        .WithMany("NotasParciais")
                        .HasForeignKey("ResultadoNotaFinalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notas_parciais_resultados_nota_finais_resultados_resultado_");

                    b.Navigation("ResultadoNotaFinal");
                });

            modelBuilder.Entity("Domain.Entities.ResultadoSessao", b =>
                {
                    b.HasOne("Domain.Entities.Sessao", "Sessao")
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessoes_resultados_sessoes_sessao_id");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("Domain.Entities.Sessao", b =>
                {
                    b.HasOne("Domain.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessoes_turmas_turma_id");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("Domain.Entities.NotaFinal", b =>
                {
                    b.Navigation("NotasParcial");
                });

            modelBuilder.Entity("Domain.Entities.Professor", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.ResultadoGrupo", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("Domain.Entities.ResultadoNotaFinal", b =>
                {
                    b.Navigation("NotasParciais");
                });

            modelBuilder.Entity("Domain.Entities.ResultadoSessao", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Criterios");

                    b.Navigation("Grupos");

                    b.Navigation("NotasFinais");
                });

            modelBuilder.Entity("Domain.Entities.Sessao", b =>
                {
                    b.Navigation("Notasfinais");
                });

            modelBuilder.Entity("Domain.Entities.Turma", b =>
                {
                    b.Navigation("Grupos");
                });
#pragma warning restore 612, 618
        }
    }
}
