// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(APIContext))]
    partial class APIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Domain.Entities.AlunoGrupo", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("AlunoId", "GrupoId");

                    b.ToTable("AlunoGrupo");
                });

            modelBuilder.Entity("Domain.Entities.AlunoTurma", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("AlunoId", "TurmaId");

                    b.HasIndex("TurmaId");

                    b.ToTable("AlunoTurma");
                });

            modelBuilder.Entity("Domain.Entities.Criterio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Criterios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Nível de Participação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Pontualidade na Entrega de Tarefas"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Capacidade de Trabalhar em Equipe"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Controle Emocional"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Disposição para Compartilhar Tarefas"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Respeito às Individualidades"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Responsabilidade"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Criatividade"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Conhecimento Teórico"
                        });
                });

            modelBuilder.Entity("Domain.Entities.CriterioTurma", b =>
                {
                    b.Property<int>("CriterioId")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("CriterioId", "TurmaId");

                    b.HasIndex("TurmaId");

                    b.ToTable("CriterioTurma");
                });

            modelBuilder.Entity("Domain.Entities.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Domain.Entities.NotaFinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceHash")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("SessaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessaoId", "AvaliadorId")
                        .IsUnique();

                    b.ToTable("NotasFinais");
                });

            modelBuilder.Entity("Domain.Entities.NotaParcial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliadoId")
                        .HasColumnType("int");

                    b.Property<int>("CriterioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Nota")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("NotaFinalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotaFinalId", "AvaliadoId", "CriterioId")
                        .IsUnique();

                    b.ToTable("NotasParciais");
                });

            modelBuilder.Entity("Domain.Entities.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenPublico")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("varchar(33)");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("Domain.Entities.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal?>("NotaMax")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("Domain.Entities.AlunoTurma", b =>
                {
                    b.HasOne("Domain.Entities.Turma", null)
                        .WithMany("AlunoTurma")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.CriterioTurma", b =>
                {
                    b.HasOne("Domain.Entities.Turma", null)
                        .WithMany("CriterioTurma")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Grupo", b =>
                {
                    b.HasOne("Domain.Entities.Turma", null)
                        .WithMany("Grupos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.NotaParcial", b =>
                {
                    b.HasOne("Domain.Entities.NotaFinal", null)
                        .WithMany("NotasParciais")
                        .HasForeignKey("NotaFinalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.NotaFinal", b =>
                {
                    b.Navigation("NotasParciais");
                });

            modelBuilder.Entity("Domain.Entities.Turma", b =>
                {
                    b.Navigation("AlunoTurma");

                    b.Navigation("CriterioTurma");

                    b.Navigation("Grupos");
                });
#pragma warning restore 612, 618
        }
    }
}
