name: Deploy Pipeline

on:
  push:
    branches: [ main, homolog ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Homolog
        if: github.ref == 'refs/heads/homolog'
        uses: superfly/flyctl-actions/fly-deploy@master
        with:
          args: "--app webav-360-homolog"
          directory: "./back" 
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        uses: superfly/flyctl-actions/fly-deploy@master
        with:
          args: "--app webav-360" 
          directory: "./back" 
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
