name: Deploy Pipeline

on:
  push:
    branches: [ main, homolog ] 

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy to Homolog
        if: github.ref == 'refs/heads/homolog'
        working-directory: ./back
        run: fly deploy --app webav-360-homolog --token ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        working-directory: ./back
        run: fly deploy --app webav-360 --token ${{ secrets.FLY_API_TOKEN }}
